version: '3.8'

services:
  wakecommerce-produto-api-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wakecommerce-produto-api-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - wakecommerce-produto-api-net

  wakecommerce-produto-api:
    build:
      context: .
      dockerfile: src/WakeCommerce.API/Dockerfile
    container_name: wakecommerce-produto-api
    depends_on:
      - wakecommerce-produto-api-db
    restart: on-failure
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=wakecommerce-produto-api-db;Database=WakeCommerceDb;User Id=sa;Password=StrongPassword@123;TrustServerCertificate=True;
    networks:
      - wakecommerce-produto-api-net

volumes:
  sql_data:

networks:
  wakecommerce-produto-api-net:
    driver: bridge