version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wakecommerce-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword@123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - wake_network

  wakecommerceapi:
    build:
      context: .
      dockerfile: src/WakeCommerce.API/Dockerfile
    container_name: wakecommerce-api
    depends_on:
      - sqlserver
    restart: on-failure
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WakeCommerceDb;User Id=sa;Password=StrongPassword@123;TrustServerCertificate=True;
    networks:
      - wake_network

volumes:
  sql_data:

networks:
  wake_network:
    driver: bridge